// ----------------------------------------------------------------------------
//		THIS CODE WAS GENERATED BY A TOOL
//		CHANGES TO THIS FILE WILL BE LOST IF THE CODE IS REGENERATED
//		Version: 1.0.0.0
//		Date: 01/24/2022 04:13:46
// ----------------------------------------------------------------------------
#pragma once
#include <cstdint>

namespace zmdb
{
	struct Position 
	{
		float x;
		float y;
		float z;
	};
	
}